# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 20:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='date published'),
        ),
    ]
