# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20170405_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporter',
            name='full_name',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
