# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20170405_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.Reporter'),
        ),
        migrations.AlterField(
            model_name='reporter',
            name='full_name',
            field=models.CharField(max_length=70),
        ),
    ]
